import 'package:flutter_bloc/flutter_bloc.dart';
import 'package:masmix/controller/share/network/endpointer.dart';
import 'package:masmix/controller/share/network/remote/dio_helper.dart';
import 'package:masmix/controller/states/easy2ship_settings_states.dart';

class Easy2shipSettingsCubit extends Cubit<Easy2shipSettingsStates> {
  Easy2shipSettingsCubit() : super(InitialEasy2shipSettingsStates());

  static Easy2shipSettingsCubit get(context) => BlocProvider.of(context);

  bool removeShoeBox = false;
  bool noImages = false;
  bool getNotifications = false;
  bool availableWalletCredit = false;
  String message = '';
  dynamic countryFlag = <String, String>{
    "ascension island": "ac",
    "andorra": "ad",
    "united arab emirates": "ae",
    "afghanistan": "af",
    "antigua and barbuda": "ag",
    "anguilla": "ai",
    "albania": "al",
    "armenia": "am",
    "angola": "ao",
    "antarctica": "aq",
    "argentina": "ar",
    "american samoa": "as",
    "austria": "at",
    "australia": "au",
    "aruba": "aw",
    "aland islands": "ax",
    "azerbaijan": "az",
    "bosnia and herzegovina": "ba",
    "barbados": "bb",
    "bangladesh": "bd",
    "belgium": "be",
    "burkina faso": "bf",
    "bulgaria": "bg",
    "bahrain": "bh",
    "burundi": "bi",
    "benin": "bj",
    "saint barth": "bl",
    "bermuda": "bm",
    "brunei": "bn",
    "bolivia": "bo",
    "bonaire": "bq",
    "brazil": "br",
    "bahamas": "bs",
    "bhutan": "bt",
    "bouvet island": "bv",
    "botswana": "bw",
    "belarus": "by",
    "belize": "bz",
    "canada": "ca",
    "cocos islands": "cc",
    "democratic republic of the congo": "cd",
    "central african republic": "cf",
    "republic of the congo": "cg",
    "switzerland": "ch",
    "c\u00f4te d'ivoire": "ci",
    "cook islands": "ck",
    "chile": "cl",
    "cameroon": "cm",
    "china": "cn",
    "colombia": "co",
    "clipperton Island": "cp",
    "costa Rica": "cr",
    "cuba": "cu",
    "cabo verde": "cv",
    "cura\u00e7ao": "cw",
    "christmas island": "cx",
    "cyprus": "cy",
    "czech republic": "cz",
    "germany": "de",
    "diego garcia": "dg",
    "djibouti": "dj",
    "denmark": "dk",
    "dominica": "dm",
    "dominican republic": "do",
    "algeria": "dz",
    "ceuta & melilla": "ea",
    "ecuador": "ec",
    "estonia": "ee",
    "egypt": "eg",
    "western sahara": "eh",
    "eritrea": "er",
    "spain": "es",
    "catalonia": "es-ct",
    "galicia": "es-ga",
    "ethiopia": "et",
    "europe": "eu",
    "finland": "fi",
    "fiji": "fj",
    "falkland islands": "fk",
    "federated states of micronesia": "fm",
    "faroe islands": "fo",
    "france": "fr",
    "gabon": "ga",
    "united kingdom": "gb",
    "england": "gb-eng",
    "northern ireland": "gb-nir",
    "scotland": "gb-sct",
    "wales": "gb-wls",
    "grenada": "gd",
    "georgia": "ge",
    "french guiana": "gf",
    "guernsey": "gg",
    "ghana": "gh",
    "gibraltar": "gi",
    "greenland": "gl",
    "gambia": "gm",
    "guinea": "gn",
    "guadeloupe": "gp",
    "equatorial guinea": "gq",
    "greece": "gr",
    "south georgia and the south sandwich islands": "gs",
    "guatemala": "gt",
    "guam": "gu",
    "guinea-bissau": "gw",
    "guyana": "gy",
    "hong kong": "hk",
    "heard island and mcDonald islands": "hm",
    "honduras": "hn",
    "croatia": "hr",
    "haiti": "ht",
    "hungary": "hu",
    "canary islands": "ic",
    "indonesia": "id",
    "ireland": "ie",
    "code": "il",
    "name": "Israel",
    "isle of man": "im",
    "india": "in",
    "british indian ocean territory": "io",
    "iraq": "iq",
    "iran": "ir",
    "iceland": "is",
    "italy": "it",
    "jersey": "je",
    "jamaica": "jm",
    "jordan": "jo",
    "japan": "jp",
    "kenya": "ke",
    "kyrgyzstan": "kg",
    "cambodia": "kh",
    "kiribati": "ki",
    "comoros": "km",
    "saint kitts and nevis": "kn",
    "north korea": "kp",
    "south korea": "kr",
    "kuwait": "kw",
    "cayman islands": "ky",
    "kazakhstan": "kz",
    "laos": "la",
    "lebanon": "lb",
    "saint lucia": "lc",
    "liechtenstein": "li",
    "sri lanka": "lk",
    "liberia": "lr",
    "lesotho": "ls",
    "lithuania": "lt",
    "luxembourg": "lu",
    "latvia": "lv",
    "libya": "ly",
    "morocco": "ma",
    "monaco": "mc",
    "moldova": "md",
    "montenegro": "me",
    "saint martin": "mf",
    "madagascar": "mg",
    "marshall islands": "mh",
    "north macedonia": "mk",
    "mali": "ml",
    "myanmar": "mm",
    "mongolia": "mn",
    "macau": "mo",
    "northern mariana islands": "mp",
    "martinique": "mq",
    "mauritania": "mr",
    "montserrat": "ms",
    "malta": "mt",
    "mauritius": "mu",
    "maldives": "mv",
    "malawi": "mw",
    "mexico": "mx",
    "malaysia": "my",
    "mozambique": "mz",
    "namibia": "na",
    "new caledonia": "nc",
    "niger": "ne",
    "norfolk island": "nf",
    "nigeria": "ng",
    "nicaragua": "ni",
    "netherlands": "nl",
    "norway": "no",
    "nepal": "np",
    "nauru": "nr",
    "niue": "nu",
    "new zealand": "nz",
    "oman": "om",
    "panama": "pa",
    "peru": "pe",
    "french polynesia": "pf",
    "papua new guinea": "pg",
    "philippines": "ph",
    "pakistan": "pk",
    "poland": "pl",
    "saint pierre and miquelon": "pm",
    "pitcairn": "pn",
    "puerto rico": "pr",
    "state of palestine": "ps",
    "portugal": "pt",
    "palau": "pw",
    "paraguay": "py",
    "qatar": "qa",
    "r\u00e9union": "re",
    "romania": "ro",
    "serbia": "rs",
    "russia": "ru",
    "rwanda": "rw",
    "saudi arabia": "sa",
    "solomon islands": "sb",
    "seychelles": "sc",
    "sudan": "sd",
    "sweden": "se",
    "singapore": "sg",
    "saint helena, ascension and tristan da cunha": "sh",
    "slovenia": "si",
    "svalbard": "sj",
    "slovakia": "sk",
    "sierra leone": "sl",
    "san marino": "sm",
    "senegal": "sn",
    "somalia": "so",
    "suriname": "sr",
    "south sudan": "ss",
    "sao tome and principe": "st",
    "El Salvador": "sv",
    "sint maarten": "sx",
    "syrian arab republic": "sy",
    "swaziland": "sz",
    "tristan da cunha": "ta",
    "turks and caicos islands": "tc",
    "chad": "td",
    "french southern territories": "tf",
    "togo": "tg",
    "thailand": "th",
    "tajikistan": "tj",
    "tokelau": "tk",
    "timor-leste": "tl",
    "turkmenistan": "tm",
    "tunisia": "tn",
    "tonga": "to",
    "turkey": "tr",
    "trinidad and tobago": "tt",
    "tuvalu": "tv",
    "taiwan": "tw",
    "tanzania": "tz",
    "ukraine": "ua",
    "uganda": "ug",
    "united states minor outlying islands": "um",
    "united nations": "un",
    "united states": "us",
    "uruguay": "uy",
    "uzbekistan": "uz",
    "holy see": "va",
    "saint vincent and the grenadines": "vc",
    "venezuela": "ve",
    "british virgin islands": "vg",
    "u.s. virgin islands": "vi",
    "vietnam": "vn",
    "vanuatu": "vu",
    "wallis and futuna": "wf",
    "samoa": "ws",
    "kosovo": "xk",
    "yemen": "ye",
    "mayotte": "yt",
    "south africa": "za",
    "zambia": "zm",
    "zimbabwe": "zw",
  };

  void changeRemoveShoeBox(value) {
    removeShoeBox = value;
    emit(ChangeRemoveShoeBoxState());
  }

  void changeNoImages(value) {
    noImages = value;
    emit(ChangeNoImagesState());
  }

  void changeGetNotifications(value) {
    getNotifications = value;
    emit(ChangeGetNotificationsState());
  }

  void changeAvailableWalletCredit(value) {
    availableWalletCredit = value;
    emit(ChangeAvailableWalletCreditState());
  }

  void upDate({required id}) {
    emit(UpDateLoadingState());
    DioHelper.postData(
      url: UpDateEasy2shipSettings,
      data: {
        "id": id,
        "remove_shoe": removeShoeBox,
        "no_images": noImages,
        "get_noti": getNotifications,
        "available_wallet": availableWalletCredit,
      },
    ).then((value) {
      message = value.data;
      emit(UpDateSuccessState());
    }).catchError((error) {
      emit(UpDateErrorState(error.toString()));
    });
  }

  String getFlag(String country){
    return countryFlag[country];
  }
}
